services:

  db:
    build: ./mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_DATABASE: gymdb
      MYSQL_USER:     gymuser
      MYSQL_PASSWORD: gympass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:            # ← NEW
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pgympass"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy   # ← NEW: wait for the health-check
    ports: ["8080:8080"]
    environment:
      SPRING_DATASOURCE_URL:      jdbc:mysql://db:3306/gymdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: gymuser
      SPRING_DATASOURCE_PASSWORD: gympass
      SERVER_PORT: 8080

volumes:
  db-data:

