# application.yml
spring:
  config:
    import: optional:dotenv:.env
  application:
    name: GymTaskREST

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/gymdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:gymuser}
    password: ${SPRING_DATASOURCE_PASSWORD:YourStrongPwd}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  output:
    ansi:
      enabled: ALWAYS

  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springfox:
  documentation:
    enabled: ${swagger.enabled:true}

logging:
  level:
    com.epam.gymapp: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    javax.management.remote: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.actuate.health: DEBUG
    com.epam.gymapp.actuator: DEBUG
    io.micrometer: DEBUG
    io.micrometer.core.instrument: DEBUG

  pattern:
    console: "%d{HH:mm:ss.SSS} %black(|) %highlight(%-4level) %black(|) %highlight(%-4.4t) %black(|) %cyan(%-35.35logger{25}) %black(|) %highlight(%m%n)"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      base-path: /ops
      path-mapping:
        health: gym-health
        prometheus: prometheus
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true


jwt:
  secret: ${JWT_SECRET:dGhpc2lzYXNlY3JldGtleWZvcnRlc3Rpbmdwb3Vwb3Nlc29ubHl9}
  expiration: ${JWT_EXPIRES_MINUTES:30}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:app}

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      MICROSERVICE-TASK:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - feign.RetryableException
          - java.io.IOException
          - java.net.SocketTimeoutException
    instances:
      MICROSERVICE-TASK:
        baseConfig: default